"""empty message

Revision ID: 6bf4dfc833d4
Revises: 
Create Date: 2024-03-21 01:23:16.939599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf4dfc833d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('num_rooms', sa.Integer(), nullable=True),
    sa.Column('num_baths', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=40), nullable=True),
    sa.Column('property_type', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('image_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
